server:
  port: 8083
  servlet:
    context-path: /p2
    
spring:
  application: 
    name: pawroledp2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://jr-postgres-hospital.postgres.database.azure.com:5432/postgres?currentSchema=pawroledp2
    username: hospitalh@jr-postgres-hospital
    password: FoolsGold69*
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web:
      exposure:
        include:
          - "beans"
          - "health"
          - "info"
   